### ISSUE TITLE
Link at "Upcoming Events" redirects to a page with 403

### ISSUE THREAD

**Issue by zonky2** [contao/contao-demo#13]
Link at "Upcoming Events"  to "Contao North-Day" https://2018.nordtag.contao.org/ link redirects to a page with 403 error

**Comment by aschempp** [comment]
That link worked when I checked the demo 😞 I'll ask the team if anyone knows about it.

**Comment by JanoschOltmanns** [comment]
The event is sold out, therefore forbidden ;-) 

There were problems with old data, so the page is currently deactivated. We will check it and activate it again.

**Comment by zonky2** [comment]
oder verlinkt Sachen, die Bestand haben...

**Comment by aschempp** [comment]
> The event is sold out, therefore forbidden ;-)

I don't understand that, the point of our year-subdomains is to keep these pages around. But I guess I don't need to care 😆

**Comment by JanoschOltmanns** [comment]
@zonky2 It seems to be fixed
