### ISSUE TITLE
Datenbank unkomprimiert bereitstellen

### ISSUE THREAD

**Issue by de-es** [contao/contao-demo#14]
Man könnte den Datenbank-Restore unkomprimiert bereitstellen, damit Änderungen auch dort versioniert werden können. Wenn man tl_undo und tl_version entfernt, bleiben noch 770kb übrig.

Es gäbe da noch ein paar kleine Optimierungen in der DB, die der Entwicklung geschuldet sind ("xxx", private Mailadressen, konsistente Titel, ...), aber ich wollte jetzt keinen PR für ein Binary machen.

**Comment by aschempp** [comment]
Ich hatte das zuerst als nicht-binary drin, allerdings sah ich dadurch keine wirklichen Vorteile. Abgesehen davon dass ein Text per Search&Replace angepasst werden könnte, ist es unmöglich in den DB-Statements die korrekte Spalte für eine Einstellung oder etwas ähnliches zu finden.

Kann `contao:database:restore` denn auch mit unkomprimierten Dateien umgehen?

**Comment by de-es** [comment]
Komplexere Änderungen hätte ich auch innerhalb von Contao gemacht, dann die DB gedumpt und in einem Diff mit der vorherigen Version die relevanten geänderten Zeilen übernommen.

Allerdings war ich davon ausgegangen, dass die Reihenfolge der Tables beim Dump immer gleich ist, was aktuell zumindest nicht so ist. (Würde dazu auch einen FR stellen, da Dumpvergleiche grds. nützlich sein können.)

`contao:database:restore` kann auch mit `.sql` umgehen, ja.
