### ISSUE TITLE
Global form styles affect debug toolbar

### ISSUE THREAD

**Issue by de-es** [contao/contao-demo#15]
![contao_debug](https://github.com/contao/contao-demo/assets/7645771/ee4be878-e816-4f35-b3b5-9e9418fa1a8d)

Betrifft grds. alle Formelemente und Links in der Toolbar, beim Grid ist es direkt auffallend.

**Comment by aschempp** [comment]
This is actually a bug that should be fixed in Contao itself, see https://github.com/contao/contao/issues/3688

**Comment by de-es** [comment]
Sicher der bessere Weg, das Problem zu lösen. Ich werde mal schauen, ob ich evtl. die Zeit finde, den vorhanden PR fit zu machen.

**Comment by zoglo** [comment]
See https://github.com/contao/contao/pull/8780 btw
