### ISSUE TITLE
Unknown options in `tl_user`

### ISSUE THREAD

**Issue by zoglo** [contao/contao-demo#17]
All users in the demo have unknown options for:

- backendTheme
- news permissions
- event permissions

![contao-demo-unknown-options](https://github.com/contao/contao-demo/assets/55794780/30617322-38dd-46b6-a32e-2034b0f62ddb)

**Comment by sascha-mueller** [comment]
@zoglo merged your pull request for 4.13. For Contao 5 I still have to add this
