### ISSUE TITLE
Form missing

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-demo#19]
May be I just haven't found it yet - but the current demo isn't demoing Contao's form generator anywhere, or is it? The database contains a "Contact" form, but it's not ouptut anywhere it seems.

**Comment by sascha-mueller** [comment]
@fritzmg The form is integrated on page /applications.html.
You will find the page below the page modules [https://demo.contao.org/applications.html](https://demo.contao.org/applications.html)

**Comment by fritzmg** [comment]
Ah there we go :)
