### ISSUE TITLE
Contao-Demo Logo

### ISSUE THREAD

**Issue by fkaminski** [contao/contao-demo#2]
In Anlehnung an das »offizielle« Contao Camp Logo,
anbei .svg Varianten (color / b&w) für die Demo (sofern erforderlich - readme?).

colored:
![logo-contao-demo-col](https://github.com/contao/contao-demo/assets/7679799/c9722694-04eb-41a7-bb47-98479db699c7)

b&w:
![logo-contao-demo-bw](https://github.com/contao/contao-demo/assets/7679799/5baa7cee-199b-408b-b7ba-6a58657860bc)

**Comment by aschempp** [comment]
die Demo hat doch bereits ein Logo? Und die offiziellen Contao Logos sind immer mit Text unterhalb von "Contao"?

**Comment by sascha-mueller** [comment]
Beide Logos haben Ihren Reiz. 
Mir gefällt sowohl Frankos Version, als auch die aktuelle, sehr schlichte Variante.
Welches Logo genutzt wird, empfinde ich eher als Entscheidung auf Basis des Team-Fokus.

Ist die Demo eher ein Community Projekt, dann wäre das C so wie die Version von Franko zu gestalten.
Liegt die Demo eher näher an Contao selbst, dann würde die jetzige Version aus meiner Sicht besser passen.

Da das Demo Team auch ein "offizielles Team" werden soll, würde ich eher zum aktuellen Logo tendieren.

**Comment by fkaminski** [comment]
Feel for use. 
Schließe das, da ja kein Issue an sich.

**Comment by aschempp** [comment]
Aus meiner Sicht (gemäss meinem Wissen vom Contao CI) ist nur das aktuelle Logo "richtig". Das hier gezeigte Logo gehört zum Contao Camp, und zu sonst nicht in der Contao Welt 😊
