### ISSUE TITLE
Users - Back end theme - Unknown option: default

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao-demo#20]
Back end users have a wrong Back end theme:
![Users-BE-Theme-wrong](https://github.com/contao/contao-demo/assets/1218809/d3d20d7f-1de5-4c5d-8b76-1aea6440e11b)

"flexible" should be set here.

Contao 5.2.8 with Demo, newly installed.

**Comment by zoglo** [comment]
Duplicate of #17
