### ISSUE TITLE
Events in calendar view aren't properly highlighted in every other row

### ISSUE THREAD

**Issue by marcelbrueckner** [contao/contao-demo#21]
As the title says, events in calendar view (e.g. https://demo.contao.org/events.html?month=202401) aren't properly highlighted in every other row.

### Current situation

<img width="1165" alt="Bildschirmfoto 2024-02-03 um 16 55 33" src="https://github.com/contao/contao-demo/assets/3597890/5c08f4d3-1e10-4e6c-a2c3-a2cccf14a5c5">

### How it should look like (I guess)

<img width="1161" alt="Bildschirmfoto 2024-02-03 um 16 55 57" src="https://github.com/contao/contao-demo/assets/3597890/385963e6-0a8e-4c7b-904f-32b3e24986e2">

**Comment by aschempp** [comment]
see https://github.com/contao/contao-demo/pull/28
