### ISSUE TITLE
Missing template layout__canvas_content.html5

### ISSUE THREAD

**Issue by landzone21** [contao/contao-demo#29]
In FE Module "layout | canvas content" I find the HTML-Code with an inserttag:

`{{file::/contaodemo/layout__canvas_content.html5}}`

But I can't find this template. The rendering in Frontend is right, but where can I find the template?

**Comment by zoglo** [comment]
Looks like an inserttag that wasn't removed

**Comment by sascha-mueller** [comment]
@zoglo is right. I will remove it with the next version
