### ISSUE TITLE
Cookiebar Plugin missing

### ISSUE THREAD

**Issue by Metis77** [contao/contao-demo#30]
I have seen `{{cookiebar::show}}` in the frontend, which makes we wonder: should the have been any cookiebar plugin installed with the demo? If yes, which one?

I suggest adding any needed plugins to the composer.json.

**Comment by zoglo** [comment]
> I suggest adding any needed plugins to the composer.json.
It's not part of the demo, this is a bug @Metis77 and shouldn't be there - Can you tell me in which version it happens? I guess 5.3.x?

**Comment by de-es** [comment]
See also https://github.com/contao/contao-demo/pull/27/commits/8335cddfb5994aee8bca9fe10048fd3e38091791

**Comment by zoglo** [comment]
Closed mine in favor of yours
