### ISSUE TITLE
PHP warning in `picture_default.html` with preview mode show all

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao-demo#37]
Contao: 4.13.43
Reason is an invalid `singleSRC` in unpublished `tl_content.id = 91`.

**Comment by Tastaturberuf** [comment]
`$this->src` is null in the template. I think Contao should check for this in the controller and preventing it.

**Comment by aschempp** [comment]
see https://github.com/contao/contao-demo/pull/38
