### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by mdollde** [contao/contao-demo#4]
Hi,
I found some typos in the new demo. I hope its ok, if I sum them up in just one issue.

Page: Home
Article: FE and BE Login
Content element: 1st text element (Front end login)
Typo: "...posibility..." --> "...possibility..."

Page: Content Elements
Article: Content Elements
Content element: 1st table element (text elements)
Typo: "Convertes markdown text to html." --> "Converts..."

Page: Text Elements
Article: Text Elements
Content element: HTML (Definition list Example)
Typo: "Buil with the Contao Content Element HTML." --> "Built..."

Page: Events
Article: Calendar
Content Element: 1st text element (Events)
"You can either use a big calendar view, a mini-calender as shown on the left side below the vertical navigation or an event-list shown at the bottom of the page." --> Mini calendar and event-list aren't placed as described --> "You can either use a big calendar view, a mini-calender or an event-list."

News
"New Contao Versions in short intervalls"
In the news teaser there is still "The last release was Contao 3.3." --> change to {{version::*}}

News
"New Contao Community Members each day"
In the news teaser: "...Therefore Contao is able to evolve contantly." --> "...constantly."

Regards
Mathias

**Comment by aschempp** [comment]
Thank you @mdollde. Fixed in ec419b398b6cd11b43759880e1123d583d52e519 and ab82ff4f8428d808ce131edb32a3e16fc51c4300
