### ISSUE TITLE
Use new accordion element

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-demo#47]
Currently the demo still uses the legacy accordion elements and has the legacy `js_accordion` template enabled in its layout. To better demonstrate the current state of Contao it should use the new accordion elements instead and disable the `js_accordion` template.

**Comment by zoglo** [comment]
Possible duplicate of #40 ?
Either way, the styles would need to be adjusted as well, unsure if this is part of the tasks that sascha wrote down

**Comment by sascha-mueller** [comment]
It is part of my updatelist

**Comment by sascha-mueller** [comment]
does it make sense to replace the legacy modules one by one or would it be better to replace everything first and then make a new version?

**Comment by fritzmg** [comment]
> Either way, the styles would need to be adjusted as well

No, why?

**Comment by zoglo** [comment]
> No, why?

Might, unsure if it simply works with Handorgel for example, didn't test it yet, if it simply works, it'd be great obviously 

> does it make sense to replace the legacy modules one by one or would it be better to replace everything first and then make a new version?

There's always just the 3 tags / versions that are `4.13.x` / `5.3.x` and `5.4.x.` (the latest changes are the new version afaik) so you could do it in steps or in one sweep

**Comment by fritzmg** [comment]
> Possible duplicate of #40 ?

Indeed, closing this as a duplicate of #40
