### ISSUE TITLE
Search-icon has no functionality

### ISSUE THREAD

**Issue by saress** [contao/contao-demo#8]
Currently the searchbar uses a background-image:

`.searchbar .widget-text:before {
    position: absolute;
    top: 50%;
    right: 1.5rem;
    z-index: 5;
    transform: translateY(-50%);
    width: 1.5rem;
    height: 1.5rem;
    background: white url(../../files/contaodemo/theme/src/img/icons/search.svg) center center no-repeat;
    content: "";
    pointer-events: none;
}`

![image](https://github.com/contao/contao-demo/assets/1481301/e3ce3588-d9b3-44e1-9253-55fb077a43df)

and the submit-button will not be displayed:

`.searchbar .widget-submit {
    display: none;
    position: absolute;
    top: 50%;
    right: 1.5rem;
    z-index: 5;
    transform: translateY(-50%);
    overflow: hidden;
    width: 1.5rem;
    height: 1.5rem;
}`

So in this case you cannot click or tap the search-icon with your mouse / fingers and you always have to use the keyboard to submit.

Kind regards,
Saress

**Comment by zoglo** [comment]
Could be closed as #12 has been merged already
