### ISSUE TITLE
Error message displacement

### ISSUE THREAD

**Issue by saress** [contao/contao-demo#9]
Hello,

when entering a wrong username / password the error message is placed somewhere:

![image](https://github.com/contao/contao-demo/assets/1481301/859084e4-2136-42e0-a43d-34d5faf1dc79)

I guess the problem depends on the position: absolute.

`form p.error {
    font-size: 0.875rem;
    line-height: 1.5;
    position: absolute;
    left: 0;
    bottom: 0;
    z-index: 5;
    margin: 0;
    color: #a30b00;
}`

Kind regards,
Saress

**Comment by zoglo** [comment]
Was fixed in #11
